spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fse_cognizant?useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: tanmay
    password: tanmay@321
  jpa:
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.use_sql_comments: true
security:
  basic:
    enabled: false
server.port: 8080